# -*- coding: utf-8 -*-
"""Codigo_Join

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122VYtJo7SfYe7VlGNtKYK703GeA0YfqZ
"""

import pandas as pd
from google.colab import files

df_2019 = pd.read_csv("/content/Investigadores_Reconocidos_por_convocatoria_20250829 (1).csv")
df_2021 = pd.read_csv("/content/Investigadores_Reconocidos_por_convocatoria_20250829 (2).csv")
df_2017 = pd.read_csv("/content/Investigadores_Reconocidos_por_convocatoria_20250829.csv")

df_total = pd.concat([df_2017, df_2019, df_2021], ignore_index=True)

excel_file = "Investigadores_Consolidado.xlsx"
df_total.to_excel(excel_file, index=False)

csv_file = "Investigadores_Consolidado.csv"
df_total.to_csv(csv_file, index=False)

files.download(excel_file)
files.download(csv_file)